

export async function up(db) {
  const categories = [
    { _id: 'cat-paper', slug: 'paper', name: 'Paper & Envelopes', description: 'Premium bond, reams, and mailing supplies' },
    { _id: 'cat-writing', slug: 'writing', name: 'Writing Instruments', description: 'Ballpoint pens, fineliners, highlighters' },
    { _id: 'cat-filing', slug: 'filing', name: 'Filing & Folders', description: 'Lever arch files, ring binders, file dividers' },
  ];

  for (const cat of categories) {
    await db.collection('categories').updateOne(
      { _id: cat._id },
      { $setOnInsert: cat },
      { upsert: true }
    );
  }

  const products = [

    {
      _id: 'SKU-PPR-A4-80G',
      name: 'Typek A4 White Copy Paper 80gsm',
      description: 'High performance multipurpose office copy paper, 500 sheets per ream',
      categoryRef: 'cat-paper',
      attributes: { paperWeight: '80gsm', packCount: 500, colour: 'White' },
      variants: ['SKU-PPR-A4-75G', 'SKU-PPR-A3-80G'],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-PPR-A4-75G',
      name: 'Rotatrim A4 White Copy Paper 75gsm',
      description: 'Reliable high-volume laser and inkjet printing paper, 500 sheets per ream',
      categoryRef: 'cat-paper',
      attributes: { paperWeight: '75gsm', packCount: 500, colour: 'White' },
      variants: ['SKU-PPR-A4-80G'],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-PPR-A3-80G',
      name: 'Typek A3 White Copy Paper 80gsm',
      description: 'Wide-format high opacity office paper, 500 sheets per ream',
      categoryRef: 'cat-paper',
      attributes: { paperWeight: '80gsm', packCount: 500, colour: 'White' },
      variants: ['SKU-PPR-A4-80G'],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-PPR-A4-COL-YLW',
      name: 'Mondi Color Copy A4 Pastel Yellow 80gsm',
      description: 'Tinted smooth office paper for notices and flyers, 500 sheets per ream',
      categoryRef: 'cat-paper',
      attributes: { paperWeight: '80gsm', packCount: 500, colour: 'Yellow' },
      variants: ['SKU-PPR-A4-COL-BLU', 'SKU-PPR-A4-COL-GRN'],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-PPR-A4-COL-BLU',
      name: 'Mondi Color Copy A4 Pastel Blue 80gsm',
      description: 'Tinted smooth office paper for color coding, 500 sheets per ream',
      categoryRef: 'cat-paper',
      attributes: { paperWeight: '80gsm', packCount: 500, colour: 'Blue' },
      variants: ['SKU-PPR-A4-COL-YLW', 'SKU-PPR-A4-COL-GRN'],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-PPR-A4-COL-GRN',
      name: 'Mondi Color Copy A4 Pastel Green 80gsm',
      description: 'Tinted smooth office paper for filing accents, 500 sheets per ream',
      categoryRef: 'cat-paper',
      attributes: { paperWeight: '80gsm', packCount: 500, colour: 'Green' },
      variants: ['SKU-PPR-A4-COL-YLW', 'SKU-PPR-A4-COL-BLU'],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-PPR-A4-160G',
      name: 'Mondi Color Copy A4 White Board 160gsm',
      description: 'Heavyweight cardstock for certificates, covers, and presentation sheets, 250 sheets',
      categoryRef: 'cat-paper',
      attributes: { paperWeight: '160gsm', packCount: 250, colour: 'White' },
      variants: [],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-ENV-DL-WS',
      name: 'Croxley DL White Self-Seal Envelopes 80gsm',
      description: 'Standard business commercial mailing envelopes 110x220mm, box of 500',
      categoryRef: 'cat-paper',
      attributes: { paperWeight: '80gsm', packCount: 500, colour: 'White' },
      variants: ['SKU-ENV-C4-WS'],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-ENV-C4-WS',
      name: 'Croxley C4 Manilla Self-Seal Pocket Envelopes',
      description: 'Heavy duty A4 document postal pocket envelopes 229x324mm, box of 250',
      categoryRef: 'cat-paper',
      attributes: { packCount: 250, colour: 'Manilla' },
      variants: ['SKU-ENV-DL-WS'],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },

    {
      _id: 'SKU-PEN-BLU-05',
      name: 'Bic Cristal Medium Ballpoint Pen Blue',
      description: 'Classic hexagonal barrel ballpoint pen with 1.0mm tip, box of 50',
      categoryRef: 'cat-writing',
      attributes: { packCount: 50, colour: 'Blue' },
      variants: ['SKU-PEN-RED-05', 'SKU-PEN-BLK-05', 'SKU-PEN-GRN-05'],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-PEN-RED-05',
      name: 'Bic Cristal Medium Ballpoint Pen Red',
      description: 'Vibrant red ink ballpoint pen with 1.0mm tungsten carbide ball, box of 50',
      categoryRef: 'cat-writing',
      attributes: { packCount: 50, colour: 'Red' },
      variants: ['SKU-PEN-BLU-05', 'SKU-PEN-BLK-05', 'SKU-PEN-GRN-05'],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-PEN-BLK-05',
      name: 'Bic Cristal Medium Ballpoint Pen Black',
      description: 'Deep black archival ink ballpoint pen with clear barrel, box of 50',
      categoryRef: 'cat-writing',
      attributes: { packCount: 50, colour: 'Black' },
      variants: ['SKU-PEN-BLU-05', 'SKU-PEN-RED-05', 'SKU-PEN-GRN-05'],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-PEN-GRN-05',
      name: 'Bic Cristal Medium Ballpoint Pen Green',
      description: 'Auditing green ink ballpoint pen with ventilated cap, box of 50',
      categoryRef: 'cat-writing',
      attributes: { packCount: 50, colour: 'Green' },
      variants: ['SKU-PEN-BLU-05', 'SKU-PEN-RED-05', 'SKU-PEN-BLK-05'],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-PEN-GEL-BLK',
      name: 'Pilot G2 0.7mm Retractable Gel Pen Black',
      description: 'Smooth dynamic gel ink rollerball pen with rubberized comfort grip, box of 12',
      categoryRef: 'cat-writing',
      attributes: { packCount: 12, colour: 'Black' },
      variants: ['SKU-PEN-GEL-BLU'],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-PEN-GEL-BLU',
      name: 'Pilot G2 0.7mm Retractable Gel Pen Blue',
      description: 'Smooth dynamic gel ink rollerball pen with rubberized comfort grip, box of 12',
      categoryRef: 'cat-writing',
      attributes: { packCount: 12, colour: 'Blue' },
      variants: ['SKU-PEN-GEL-BLK'],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-MRK-WBD-AST',
      name: 'Artline 5109A Whiteboard Markers Assorted',
      description: 'Dense pigment dry-erase whiteboard markers with bullet nib, wallet of 4',
      categoryRef: 'cat-writing',
      attributes: { packCount: 4, colour: 'Assorted' },
      variants: [],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-HLT-YEL-01',
      name: 'Faber-Castell Textliner 48 Highlighter Yellow',
      description: 'Universal water-based fluorescent highlighter with chisel tip, box of 10',
      categoryRef: 'cat-writing',
      attributes: { packCount: 10, colour: 'Yellow' },
      variants: [],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },

    {
      _id: 'SKU-FIL-LVR-BLK',
      name: 'Bantex Lever Arch File 70mm A4 Black',
      description: 'Durable marbled paperboard lever arch filing mechanism with spine label',
      categoryRef: 'cat-filing',
      attributes: { colour: 'Black' },
      variants: ['SKU-FIL-LVR-BLU', 'SKU-FIL-LVR-RED', 'SKU-FIL-LVR-GRN'],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-FIL-LVR-BLU',
      name: 'Bantex Lever Arch File 70mm A4 Blue',
      description: 'Reinforced polypropylene spine lever arch file with rado locking system',
      categoryRef: 'cat-filing',
      attributes: { colour: 'Blue' },
      variants: ['SKU-FIL-LVR-BLK', 'SKU-FIL-LVR-RED', 'SKU-FIL-LVR-GRN'],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-FIL-LVR-RED',
      name: 'Bantex Lever Arch File 70mm A4 Red',
      description: 'Reinforced polypropylene spine lever arch file with rado locking system',
      categoryRef: 'cat-filing',
      attributes: { colour: 'Red' },
      variants: ['SKU-FIL-LVR-BLK', 'SKU-FIL-LVR-BLU', 'SKU-FIL-LVR-GRN'],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-FIL-LVR-GRN',
      name: 'Bantex Lever Arch File 70mm A4 Green',
      description: 'Reinforced polypropylene spine lever arch file with rado locking system',
      categoryRef: 'cat-filing',
      attributes: { colour: 'Green' },
      variants: ['SKU-FIL-LVR-BLK', 'SKU-FIL-LVR-BLU', 'SKU-FIL-LVR-RED'],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-FIL-RNG-BLK',
      name: 'Bantex 2-Ring Binder 25mm A4 Black',
      description: 'Heavy gauge PVC 2 O-ring document presentation binder with clear pocket',
      categoryRef: 'cat-filing',
      attributes: { colour: 'Black' },
      variants: [],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-FIL-DIV-10T',
      name: 'Croxley Mylar Index Dividers 1-10 Tab A4',
      description: 'Reinforced multi-punched plastic index tab dividers for filing systems, 1-10 tabs',
      categoryRef: 'cat-filing',
      attributes: { packCount: 10, colour: 'Assorted' },
      variants: ['SKU-FIL-DIV-31T'],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-FIL-DIV-31T',
      name: 'Croxley Mylar Index Dividers 1-31 Tab A4',
      description: 'Reinforced monthly daily index dividers numbered 1-31 for audit files',
      categoryRef: 'cat-filing',
      attributes: { packCount: 31, colour: 'Assorted' },
      variants: ['SKU-FIL-DIV-10T'],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'SKU-FIL-PPC-A4',
      name: 'Bantex Polypropylene Sheet Protectors A4',
      description: 'Crystal clear top opening embossed sheet protectors with reinforced spine, pack of 100',
      categoryRef: 'cat-filing',
      attributes: { packCount: 100, colour: 'Clear' },
      variants: [],
      mediaRefs: [],
      active: true,
      updatedAt: new Date().toISOString(),
    },
  ];

  for (const prod of products) {
    await db.collection('products').updateOne(
      { _id: prod._id },
      { $setOnInsert: prod },
      { upsert: true }
    );
  }
}
